name: Static Analysis

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  static-analysis-phpstan:
    name: Static Analysis with PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: 8.1
          extensions: mbstring

      - name: Composer install
        uses: ramsey/composer-install@v3

      - name: Run a static analysis with phpstan/phpstan
        run: vendor/bin/phpstan analyse
