name: Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    name: Tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.3
          - 7.4
          - 8.0
          - 8.1
          - 8.2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: xdebug
          php-version: ${{ matrix.php-version }}
          extensions: mbstring

      - name: Composer install
        uses: ramsey/composer-install@v2

      - name: Run PHPUnit
        run: vendor/bin/phpunit --coverage-clover=clover.xml

      - name: Upload codecov coverage reporter
        if: matrix.php-version == '8.2'
        uses: codecov/codecov-action@v2
        with:
          files: clover.xml

      - name: Upload codacy coverage reporter
        if: matrix.php-version == '8.2'
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: clover.xml
